[package]
name = "rhdl"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Write firmware for FPGAs in Rust (formerly rust-hdl)"
homepage = "https://rhdl.org"
repository = "https://github.com/samitbasu/rhdl"
keywords = ["fpga", "hdl", "verilog", "hardware"]
authors = ["Samit Basu <basu.samit@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rhdl-bits = { path = "../rhdl-bits" }
rhdl-core = { path = "../rhdl-core", features = ["iverilog"] }
rhdl-macro = { version = "0.0.2", path = "../rhdl-macro" }
anyhow = "1.0.75"
svg = { version = "0.14.0", optional = true }
serde_json = "1.0.64"
petgraph = "0.6.4"
miette = { version = "7.2.0", features = ["fancy"] }

[features]
svg = ["rhdl-core/svg", "dep:svg"]

[dev-dependencies]
itertools = "0.12.0"
rand = "0.8.5"
env_logger = "0.11.5"
log = "0.4.22"
expect-test = "1.5.0"

[profile.test]
inherits = "release"
